Profile pins
LBPUnion/project-lighthouse pull request #35
Opened 2021-11-02 08:50 UTC by LumaLivy

Adds support for setting profile pins.

### Some notes:
- Tested in LBP2, RPCS3 environment
- Added a new class under Profile in Types for "Pins", because I needed a class in order to deserialize the JSON request body being posted. Hopefully this is the appropriate place to put it.
- If there is a better way to grab the profile_pins key from the `update_my_pins` request without the Pins class, or the class needs more (like the `Serialize` method or xml attributes seen in other "Types"), please let me know. I'm familiarizing myself with C# so I picked a relatively simple task to undertake.
- I'm not sure if the progress and awards fields are used for online play because the `profile_pins` are what's being set in the actual profile. No database changes are needed for my additions because the joined `profile_pins` string is being set in `User.Pins`

2021-11-02 22:44 UTC, jvyden requested changes

2021-11-02 22:44 UTC, jvyden commented on ProjectLighthouse/Types/Profiles/Pins.cs
> +        public long[] profile_pins { get; set; }
You can keep the naming style of the JSON data while also keeping the naming style of C# using a `JsonPropertyName` attribute.
Heres a (modified) example [from the Microsoft wiki](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-customize-properties?pivots=dotnet-5-0#customize-individual-property-names):
```csharp
[JsonPropertyName("wind_speed")]
public int WindSpeed { get; set; }
```

2021-11-02 22:44 UTC, jvyden commented
Pretty good! Just one thing, as showed above.

2021-11-02 22:50 UTC, jvyden commented
@github-actions whats your deal run the damn tests

2021-11-03 00:06 UTC, LumaLivy commented
That should do it. Thanks for the pointer!

2021-11-03 00:28 UTC, jvyden commented
Looks good to me, thanks for your contribution!

2021-11-03 00:28 UTC, merged

2022-08-16 12:16 UTC, TorutheRedFox commented
the progress and awards are used to award specific pins, and seemingly to carry pins over from LBP2 to LBP3?